AWSTemplateFormatVersion: "2010-09-09"
Description: Create a DataSync Task
Parameters:
  DataSyncAgentArn:
    Description: "The ARN key of the activated DataSync agent"
    Type: String
  SourceNfsServer:
    Description: "The hostname or IP address of the source NFS server"
    Type: String
  SourceNfsPath:
    Description: "The path to copy data from on the source NFS server"
    Type: String
    Default: "/"
  TargetS3BucketArn:
    Description: "The ARN of the S3 Bucket to use for the target location"
    Type: String
  OdsCode:
    Description: "The ODS Code of the practice being migrated"
    Type: String

Resources:
  SourceNfsLocation:
    Type: AWS::DataSync::LocationNFS
    Properties:
      OnPremConfig:
        AgentArns:
          - !Ref DataSyncAgentArn
      ServerHostname: !Ref SourceNfsServer
      Subdirectory: !Ref SourceNfsPath
  TargetS3BucketAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - datasync.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Description: "Role to allow DataSync to access an S3 bucket for a practice migration"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      MaxSessionDuration: 3600
      RoleName:
        !Join [
          "-",
          [
            "AllowDataSyncAccessToS3",
            !Join [
              "-",
              [
                !Ref OdsCode,
                !Select [
                  4,
                  !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]],
                ],
              ],
            ],
          ],
        ]
  TargetLocation:
    Type: AWS::DataSync::LocationS3
    Properties:
      S3BucketArn: !Ref TargetS3BucketArn
      S3Config:
        BucketAccessRoleArn: !GetAtt TargetS3BucketAccessRole.Arn
      S3StorageClass: STANDARD
      Subdirectory:
        !Join [
          "-",
          [
            !Ref OdsCode,
            !Select [
              4,
              !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]],
            ],
          ],
        ]
  DataSyncTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        !Join [
          "-",
          [
            !Ref OdsCode,
            !Select [
              4,
              !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]],
            ],
          ],
        ]
      RetentionInDays: 60
  DataSyncTask:
    Type: AWS::DataSync::Task
    Properties:
      CloudWatchLogGroupArn: !GetAtt DataSyncTaskLogGroup.Arn
      DestinationLocationArn: !GetAtt TargetLocation.LocationArn
      Name:
        !Join [
          "-",
          [
            !Ref OdsCode,
            !Select [
              4,
              !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]],
            ],
          ],
        ]
      SourceLocationArn: !GetAtt SourceNfsLocation.LocationArn

Outputs:
  TaskArn:
    Description: The ARN of the created DataSync Task
    Value: !Ref DataSyncTask
