format_version: 4
pipelines:
  "prm-practice-migration-datasync-pipeline":
    group: practice-migrations
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build_test_env:
          approval: manual
          clean_workspace: true
          jobs:
            create_source_network:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks create_source_network "pracmig-bastion" "127.0.0.1/32"
