AWSTemplateFormatVersion: "2010-09-09"
Description: Create a DataSync Task
Parameters:
  # ActivationKey:
  #   Description: "The activation key of the activated DataSync agent"
  #   Type: String
  # SourceNfsServer:
  #   Description: "The hostname or IP address of the source NFS server"
  #   Type: String
  # SourceNfsPath:
  #   Description: "The path to copy data from on the source NFS server"
  #   Type: String
  #   Default: "/"
  TargetS3BucketArn:
    Description: "The ARN of the S3 Bucket to use for the target location"
    Type: String
  OdsCode:
    Description: "The ODS Code of the practice being migrated"
    Type: String
  # LogGroupArn:
  #   Description: "The ARN of the CloudWatch log group that DataSync will log to"
  #   Type: String

Resources:
  TargetS3BucketAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - datasync.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Description: "Role to allow DataSync to access an S3 bucket for a practice migration"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      MaxSessionDuration: 3600
      Path:
        !Join [
          "/",
          [
            "",
            !Join [
              "-",
              [
                !Ref OdsCode,
                !Select [
                  4,
                  !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]],
                ],
              ],
            ],
            "",
          ],
        ]
      RoleName: "AllowDataSyncAccessToS3"
  TargetLocation:
    Type: AWS::DataSync::LocationS3
    Properties:
      S3BucketArn: !Ref TargetS3BucketArn
      S3Config:
        BucketAccessRoleArn: !GetAtt TargetS3BucketAccessRole.Arn
      S3StorageClass: STANDARD
      Subdirectory:
        !Join [
          "-",
          [
            !Ref OdsCode,
            !Select [
              4,
              !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]],
            ],
          ],
        ]
