#!/bin/bash

set -Eeo pipefail

command="${1}"
case "${command}" in
    _create_source_network)
        cd "pracmig-create-datasync-task"
        ./scripts/deploy-source-supplier-network.sh \
            -k "${2}" \
            -c "${3}" \
            -i "gocd-${GO_PIPELINE_COUNTER}"

        ;;
    create_source_network)
        dojo "./pracmig-create-datasync-task/tasks _create_source_network ${2:?Key-pair name required} ${3:?CIDR range required}"
        ;;
    *)
        echo "Invalid command: '${command}'"
        exit 1
        ;;
esac

set +e